Bug fix/knite 1113 style issues
MO-Movia/licit-ui-commands pull request #152
Opened 2024-07-30 14:17 UTC by rohanrjohn

2024-07-31 16:03 UTC, Tezra requested changes

2024-07-31 16:03 UTC, Tezra commented on src/ui/PopUpManager.ts
> +/* eslint-disable */
No disable

2024-07-31 16:03 UTC, Tezra commented on src/ui/PopUpManager.ts
>      while (true) {
why isn't this a do-while loop?

2024-08-05 17:24 UTC, Tezra commented
@rohanrjohn there are some sonar issues that need to be fixed. In particular we really need to fix the deprecated react render issues. The rest of the issues look like they should be really quick to fix.

2024-08-12 11:35 UTC, Tezra requested changes
Linting is failing.

After failing the build I also merged in the weekly dep updates.

2024-08-23 11:54 UTC, closed without merging

2024-08-23 11:55 UTC, rohanrjohn commented
Closing pull request as the functionality seems to be breaking after the sonar fixes.