Unit tests
MO-Movia/licit-ui-commands pull request #25
Opened 2023-08-30 12:52 UTC by Jayakrishnan-MS

Test coverage with above 80%

2023-08-31 11:43 UTC, Tezra requested changes

2023-08-31 11:43 UTC, Tezra commented on package.json
> +    "@modusoperandi/licit-doc-attrs-step": "^0.1.6",
needs to be ^0.1.5

2023-08-31 11:43 UTC, Tezra commented on src/HeadingCommand.test.ts
> +    command.execute(state);
missing expect

2023-08-31 11:43 UTC, Tezra commented on src/IndentCommand.test.ts
> +
way too much extra white space

2023-08-31 11:43 UTC, Tezra commented on src/TextAlignCommand.test.ts
> +    command.execute(state, dispatch);
missing expect

2023-08-31 11:43 UTC, Tezra commented on src/TextAlignCommand.test.ts
> +    command.execute(state);
missing expect

2023-08-31 11:43 UTC, Tezra commented on src/TextLineSpacingCommand.ts
> +      dispatch(tr as Transaction);
Typescript has a null safe noop. Replace all instances of noop with dispatch?.(tr)

2023-08-31 11:43 UTC, Tezra commented on src/ui/PointerSurface.test.tsx
> +    shallow(<PointerSurface />);
missing expect

2023-08-31 11:43 UTC, Tezra commented on src/ui/PointerSurface.test.tsx
> +    shallow(<PointerSurface />);
There is an expect for no errors that will give clearer test failure messages

2023-08-31 11:43 UTC, Tezra commented on src/ui/PopUp.test.tsx
> +
double beforeEach and afterEach. merge them.

2023-09-07 11:30 UTC, Tezra requested changes
Tests failing "Schema is missing its top node type ('doc')"

2023-09-18 13:42 UTC, Tezra approved these changes

2023-09-18 14:26 UTC, rodgersgb approved these changes

2023-09-18 14:26 UTC, merged